import { neon } from "@neondatabase/serverless";
import { drizzle } from "drizzle-orm/neon-http";
import dotenv from "dotenv";
import * as schema from "../src/lib/db/schemas/index.js";

dotenv.config();

const databaseUrl = process.env.DATABASE_URL;
if (!databaseUrl) {
  console.error("DATABASE_URL environment variable is not set");
  process.exit(1);
}

const sql = neon(databaseUrl);
const db = drizzle(sql, { schema });

const COUNCILS = [
  { councilNumber: 1, name: "Greater Alabama Council", headquartersCity: "Birmingham", headquartersState: "Alabama" },
  { councilNumber: 3, name: "Alabama-Florida Council", headquartersCity: "Dothan", headquartersState: "Alabama" },
  { councilNumber: 4, name: "Mobile Area Council", headquartersCity: "Mobile", headquartersState: "Alabama" },
  { councilNumber: 5, name: "Tukabatchee Area Council", headquartersCity: "Montgomery", headquartersState: "Alabama" },
  { councilNumber: 6, name: "Black Warrior Council", headquartersCity: "Tuscaloosa", headquartersState: "Alabama" },
  { councilNumber: 10, name: "Grand Canyon Council", headquartersCity: "Phoenix", headquartersState: "Arizona" },
  { councilNumber: 11, name: "Catalina Council", headquartersCity: "Tucson", headquartersState: "Arizona" },
  { councilNumber: 18, name: "Natural State Council", headquartersCity: "Little Rock", headquartersState: "Arkansas" },
  { councilNumber: 23, name: "Golden Gate Area Council", headquartersCity: "Pleasant Hill", headquartersState: "California" },
  { councilNumber: 27, name: "Sequoia Council", headquartersCity: "Fresno", headquartersState: "California" },
  { councilNumber: 30, name: "Southern Sierra Council", headquartersCity: "Bakersfield", headquartersState: "California" },
  { councilNumber: 31, name: "Pacific Skyline Council", headquartersCity: "Foster City", headquartersState: "California" },
  { councilNumber: 32, name: "Long Beach Area Council", headquartersCity: "Long Beach", headquartersState: "California" },
  { councilNumber: 33, name: "Greater Los Angeles Area Council", headquartersCity: "Los Angeles", headquartersState: "California" },
  { councilNumber: 35, name: "Marin Council", headquartersCity: "San Rafael", headquartersState: "California" },
  { councilNumber: 39, name: "Orange County Council", headquartersCity: "Santa Ana", headquartersState: "California" },
  { councilNumber: 41, name: "Redwood Empire Council", headquartersCity: "Santa Rosa", headquartersState: "California" },
  { councilNumber: 42, name: "Piedmont Council", headquartersCity: "Piedmont", headquartersState: "California" },
  { councilNumber: 45, name: "California Inland Empire Council", headquartersCity: "Redlands", headquartersState: "California" },
  { councilNumber: 47, name: "Golden Empire Council", headquartersCity: "Sacramento", headquartersState: "California" },
  { councilNumber: 49, name: "San Diego-Imperial Council", headquartersCity: "San Diego", headquartersState: "California" },
  { councilNumber: 51, name: "Western Los Angeles County Council", headquartersCity: "Van Nuys", headquartersState: "California" },
  { councilNumber: 53, name: "Los Padres Council", headquartersCity: "Santa Barbara", headquartersState: "California" },
  { councilNumber: 55, name: "Silicon Valley Monterey Bay Council", headquartersCity: "San Jose", headquartersState: "California" },
  { councilNumber: 57, name: "Ventura County Council", headquartersCity: "Camarillo", headquartersState: "California" },
  { councilNumber: 58, name: "Verdugo Hills Council", headquartersCity: "Glendale", headquartersState: "California" },
  { councilNumber: 59, name: "Greater Yosemite Council", headquartersCity: "Modesto", headquartersState: "California" },
  { councilNumber: 60, name: "Pathway to the Rockies Council", headquartersCity: "Colorado Springs", headquartersState: "Colorado" },
  { councilNumber: 61, name: "Greater Colorado Council", headquartersCity: "Denver", headquartersState: "Colorado" },
  { councilNumber: 62, name: "Adventure West Council", headquartersCity: "Greeley", headquartersState: "Colorado" },
  { councilNumber: 66, name: "Connecticut Rivers Council", headquartersCity: "East Hartford", headquartersState: "Connecticut" },
  { councilNumber: 67, name: "Greenwich Council", headquartersCity: "Greenwich", headquartersState: "Connecticut" },
  { councilNumber: 69, name: "Housatonic Council", headquartersCity: "Derby", headquartersState: "Connecticut" },
  { councilNumber: 70, name: "Old North State Council", headquartersCity: "Greensboro", headquartersState: "North Carolina" },
  { councilNumber: 72, name: "Connecticut Yankee Council", headquartersCity: "Milford", headquartersState: "Connecticut" },
  { councilNumber: 81, name: "Del-Mar-Va Council", headquartersCity: "Dover", headquartersState: "Delaware" },
  { councilNumber: 82, name: "National Capital Area Council", headquartersCity: "Bethesda", headquartersState: "Maryland" },
  { councilNumber: 83, name: "Central Florida Council", headquartersCity: "Apopka", headquartersState: "Florida" },
  { councilNumber: 84, name: "South Florida Council", headquartersCity: "Miami Lakes", headquartersState: "Florida" },
  { councilNumber: 85, name: "Gulf Stream Council", headquartersCity: "Palm Beach Gardens", headquartersState: "Florida" },
  { councilNumber: 87, name: "North Florida Council", headquartersCity: "Jacksonville", headquartersState: "Florida" },
  { councilNumber: 88, name: "Southwest Florida Council", headquartersCity: "Fort Myers", headquartersState: "Florida" },
  { councilNumber: 89, name: "Greater Tampa Bay Area Council", headquartersCity: "Tampa", headquartersState: "Florida" },
  { councilNumber: 91, name: "Chattahoochee Council", headquartersCity: "Columbus", headquartersState: "Georgia" },
  { councilNumber: 92, name: "Atlanta Area Council", headquartersCity: "Atlanta", headquartersState: "Georgia" },
  { councilNumber: 93, name: "Georgia-Carolina Council", headquartersCity: "Augusta", headquartersState: "Georgia" },
  { councilNumber: 95, name: "Flint River Council", headquartersCity: "Griffin", headquartersState: "Georgia" },
  { councilNumber: 96, name: "Central Georgia Council", headquartersCity: "Macon", headquartersState: "Georgia" },
  { councilNumber: 98, name: "South Georgia Council", headquartersCity: "Valdosta", headquartersState: "Georgia" },
  { councilNumber: 99, name: "Coastal Georgia Council", headquartersCity: "Savannah", headquartersState: "Georgia" },
  { councilNumber: 100, name: "Northwest Georgia Council", headquartersCity: "Rome", headquartersState: "Georgia" },
  { councilNumber: 101, name: "Northeast Georgia Council", headquartersCity: "Jefferson", headquartersState: "Georgia" },
  { councilNumber: 104, name: "Aloha Council", headquartersCity: "Honolulu", headquartersState: "Hawaii" },
  { councilNumber: 106, name: "Mountain West Council", headquartersCity: "Boise", headquartersState: "Idaho" },
  { councilNumber: 107, name: "Grand Teton Council", headquartersCity: "Idaho Falls", headquartersState: "Idaho" },
  { councilNumber: 117, name: "Prairielands Council", headquartersCity: "Champaign", headquartersState: "Illinois" },
  { councilNumber: 127, name: "Three Fires Council", headquartersCity: "St Charles", headquartersState: "Illinois" },
  { councilNumber: 129, name: "Northeast Illinois Council", headquartersCity: "Highland Park", headquartersState: "Illinois" },
  { councilNumber: 133, name: "Illowa Council", headquartersCity: "Davenport", headquartersState: "Iowa" },
  { councilNumber: 138, name: "W. D. Boyce Council", headquartersCity: "Peoria", headquartersState: "Illinois" },
  { councilNumber: 141, name: "Mississippi Valley Council", headquartersCity: "Quincy", headquartersState: "Illinois" },
  { councilNumber: 144, name: "Abraham Lincoln Council", headquartersCity: "Springfield", headquartersState: "Illinois" },
  { councilNumber: 145, name: "Hoosier Trails Council", headquartersCity: "Bloomington", headquartersState: "Indiana" },
  { councilNumber: 156, name: "Buffalo Trace Council", headquartersCity: "Evansville", headquartersState: "Indiana" },
  { councilNumber: 157, name: "Anthony Wayne Area Council", headquartersCity: "Fort Wayne", headquartersState: "Indiana" },
  { councilNumber: 160, name: "Crossroads of America Council", headquartersCity: "Indianapolis", headquartersState: "Indiana" },
  { councilNumber: 162, name: "Sagamore Council", headquartersCity: "Kokomo", headquartersState: "Indiana" },
  { councilNumber: 165, name: "La Salle Council", headquartersCity: "South Bend", headquartersState: "Indiana" },
  { councilNumber: 172, name: "Hawkeye Area Council", headquartersCity: "Cedar Rapids", headquartersState: "Iowa" },
  { councilNumber: 173, name: "Winnebago Council", headquartersCity: "Waterloo", headquartersState: "Iowa" },
  { councilNumber: 177, name: "Mid-Iowa Council", headquartersCity: "Des Moines", headquartersState: "Iowa" },
  { councilNumber: 178, name: "Northeast Iowa Council", headquartersCity: "Dubuque", headquartersState: "Iowa" },
  { councilNumber: 192, name: "Coronado Area Council", headquartersCity: "Salina", headquartersState: "Kansas" },
  { councilNumber: 197, name: "Jayhawk Area Council", headquartersCity: "Topeka", headquartersState: "Kansas" },
  { councilNumber: 198, name: "Quivira Council", headquartersCity: "Wichita", headquartersState: "Kansas" },
  { councilNumber: 204, name: "Blue Grass Council", headquartersCity: "Lexington", headquartersState: "Kentucky" },
  { councilNumber: 205, name: "Lincoln Heritage Council", headquartersCity: "Louisville", headquartersState: "Kentucky" },
  { councilNumber: 209, name: "Calcasieu Area Council", headquartersCity: "Lake Charles", headquartersState: "Louisiana" },
  { councilNumber: 211, name: "Istrouma Area Council", headquartersCity: "Baton Rouge", headquartersState: "Louisiana" },
  { councilNumber: 212, name: "Evangeline Area Council", headquartersCity: "Lafayette", headquartersState: "Louisiana" },
  { councilNumber: 213, name: "Louisiana Purchase Council", headquartersCity: "Monroe", headquartersState: "Louisiana" },
  { councilNumber: 214, name: "Southeast Louisiana Council", headquartersCity: "Metairie", headquartersState: "Louisiana" },
  { councilNumber: 215, name: "Norwela Council", headquartersCity: "Shreveport", headquartersState: "Louisiana" },
  { councilNumber: 216, name: "Katahdin Area Council", headquartersCity: "Orono", headquartersState: "Maine" },
  { councilNumber: 218, name: "Pine Tree Council", headquartersCity: "Portland", headquartersState: "Maine" },
  { councilNumber: 220, name: "Baltimore Area Council", headquartersCity: "Baltimore", headquartersState: "Maryland" },
  { councilNumber: 224, name: "Cape Cod and the Islands Council", headquartersCity: "Yarmouth Port", headquartersState: "Massachusetts" },
  { councilNumber: 227, name: "Spirit of Adventure Council", headquartersCity: "Woburn", headquartersState: "Massachusetts" },
  { councilNumber: 230, name: "Heart of New England Council", headquartersCity: "Rutland", headquartersState: "Massachusetts" },
  { councilNumber: 234, name: "Western Massachusetts Council", headquartersCity: "Westfield", headquartersState: "Massachusetts" },
  { councilNumber: 250, name: "Northern Star Council", headquartersCity: "Saint Paul", headquartersState: "Minnesota" },
  { councilNumber: 251, name: "Mayflower Council", headquartersCity: "Milford", headquartersState: "Massachusetts" },
  { councilNumber: 283, name: "Twin Valley Council", headquartersCity: "Mankato", headquartersState: "Minnesota" },
  { councilNumber: 296, name: "Central Minnesota Council", headquartersCity: "Sartell", headquartersState: "Minnesota" },
  { councilNumber: 299, name: "Gamehaven Council", headquartersCity: "Rochester", headquartersState: "Minnesota" },
  { councilNumber: 302, name: "Choctaw Area Council", headquartersCity: "Meridian", headquartersState: "Mississippi" },
  { councilNumber: 303, name: "Andrew Jackson Council", headquartersCity: "Jackson", headquartersState: "Mississippi" },
  { councilNumber: 304, name: "Pine Burr Area Council", headquartersCity: "Hattiesburg", headquartersState: "Mississippi" },
  { councilNumber: 306, name: "Ozark Trails Council", headquartersCity: "Springfield", headquartersState: "Missouri" },
  { councilNumber: 307, name: "Heart of America Council", headquartersCity: "Kansas City", headquartersState: "Missouri" },
  { councilNumber: 311, name: "Pony Express Council", headquartersCity: "Saint Joseph", headquartersState: "Missouri" },
  { councilNumber: 312, name: "Greater Saint Louis Area Council", headquartersCity: "Saint Louis", headquartersState: "Missouri" },
  { councilNumber: 315, name: "Montana Council", headquartersCity: "Great Falls", headquartersState: "Montana" },
  { councilNumber: 324, name: "Cornhusker Council", headquartersCity: "Walton", headquartersState: "Nebraska" },
  { councilNumber: 326, name: "Mid-America Council", headquartersCity: "Omaha", headquartersState: "Nebraska" },
  { councilNumber: 328, name: "Las Vegas Area Council", headquartersCity: "Las Vegas", headquartersState: "Nevada" },
  { councilNumber: 329, name: "Nevada Area Council", headquartersCity: "Reno", headquartersState: "Nevada" },
  { councilNumber: 330, name: "Daniel Webster Council", headquartersCity: "Manchester", headquartersState: "New Hampshire" },
  { councilNumber: 333, name: "Northern New Jersey Council", headquartersCity: "Oakland", headquartersState: "New Jersey" },
  { councilNumber: 341, name: "Jersey Shore Council", headquartersCity: "Toms River", headquartersState: "New Jersey" },
  { councilNumber: 347, name: "Monmouth Council", headquartersCity: "Morganville", headquartersState: "New Jersey" },
  { councilNumber: 358, name: "Patriots' Path Council", headquartersCity: "Cedar Knolls", headquartersState: "New Jersey" },
  { councilNumber: 364, name: "Twin Rivers Council", headquartersCity: "Albany", headquartersState: "New York" },
  { councilNumber: 368, name: "Baden-Powell Council", headquartersCity: "Binghamton", headquartersState: "New York" },
  { councilNumber: 373, name: "Longhouse Council", headquartersCity: "Syracuse", headquartersState: "New York" },
  { councilNumber: 380, name: "Great Falls Council", headquartersCity: "Buffalo", headquartersState: "New York" },
  { councilNumber: 382, name: "Allegheny Highlands Council", headquartersCity: "Falconer", headquartersState: "New York" },
  { councilNumber: 386, name: "Theodore Roosevelt Council", headquartersCity: "Massapequa", headquartersState: "New York" },
  { councilNumber: 388, name: "Greater Hudson Valley Council", headquartersCity: "Fishkill", headquartersState: "New York" },
  { councilNumber: 397, name: "Seneca Waterways Council", headquartersCity: "Rochester", headquartersState: "New York" },
  { councilNumber: 400, name: "Leatherstocking Council", headquartersCity: "Utica", headquartersState: "New York" },
  { councilNumber: 404, name: "Suffolk County Council", headquartersCity: "Medford", headquartersState: "New York" },
  { councilNumber: 405, name: "Rip Van Winkle Council", headquartersCity: "Kingston", headquartersState: "New York" },
  { councilNumber: 412, name: "High Desert Council", headquartersCity: "Albuquerque", headquartersState: "New Mexico" },
  { councilNumber: 413, name: "Conquistador Council", headquartersCity: "Roswell", headquartersState: "New Mexico" },
  { councilNumber: 414, name: "Daniel Boone Council", headquartersCity: "Asheville", headquartersState: "North Carolina" },
  { councilNumber: 415, name: "Mecklenburg County Council", headquartersCity: "Charlotte", headquartersState: "North Carolina" },
  { councilNumber: 416, name: "Central North Carolina Council", headquartersCity: "Albemarle", headquartersState: "North Carolina" },
  { councilNumber: 420, name: "Piedmont Council", headquartersCity: "Gastonia", headquartersState: "North Carolina" },
  { councilNumber: 421, name: "Occoneechee Council", headquartersCity: "Raleigh", headquartersState: "North Carolina" },
  { councilNumber: 424, name: "Tuscarora Council", headquartersCity: "Goldsboro", headquartersState: "North Carolina" },
  { councilNumber: 425, name: "Cape Fear Council", headquartersCity: "Wilmington", headquartersState: "North Carolina" },
  { councilNumber: 426, name: "East Carolina Council", headquartersCity: "Kinston", headquartersState: "North Carolina" },
  { councilNumber: 427, name: "Old Hickory Council", headquartersCity: "Winston-Salem", headquartersState: "North Carolina" },
  { councilNumber: 429, name: "Northern Lights Council", headquartersCity: "Fargo", headquartersState: "North Dakota" },
  { councilNumber: 433, name: "Great Trail Council", headquartersCity: "Akron", headquartersState: "Ohio" },
  { councilNumber: 436, name: "Buckeye Council", headquartersCity: "Canton", headquartersState: "Ohio" },
  { councilNumber: 438, name: "Dan Beard Council", headquartersCity: "Cincinnati", headquartersState: "Ohio" },
  { councilNumber: 439, name: "Tecumseh Council", headquartersCity: "Springfield", headquartersState: "Ohio" },
  { councilNumber: 440, name: "Lake Erie Council", headquartersCity: "Cleveland", headquartersState: "Ohio" },
  { councilNumber: 441, name: "Simon Kenton Council", headquartersCity: "Columbus", headquartersState: "Ohio" },
  { councilNumber: 444, name: "Miami Valley Council", headquartersCity: "Dayton", headquartersState: "Ohio" },
  { councilNumber: 449, name: "Black Swamp Area Council", headquartersCity: "Findlay", headquartersState: "Ohio" },
  { councilNumber: 456, name: "Pathway to Adventure Council", headquartersCity: "Chicago", headquartersState: "Illinois" },
  { councilNumber: 460, name: "Erie Shores Council", headquartersCity: "Toledo", headquartersState: "Ohio" },
  { councilNumber: 467, name: "Muskingum Valley Council", headquartersCity: "Zanesville", headquartersState: "Ohio" },
  { councilNumber: 468, name: "Arbuckle Area Council", headquartersCity: "Ardmore", headquartersState: "Oklahoma" },
  { councilNumber: 469, name: "Cherokee Area Council", headquartersCity: "Bartlesville", headquartersState: "Oklahoma" },
  { councilNumber: 480, name: "Last Frontier Council", headquartersCity: "Oklahoma City", headquartersState: "Oklahoma" },
  { councilNumber: 488, name: "Indian Nations Council", headquartersCity: "Tulsa", headquartersState: "Oklahoma" },
  { councilNumber: 492, name: "Cascade Pacific Council", headquartersCity: "Beaverton", headquartersState: "Oregon" },
  { councilNumber: 497, name: "Juniata Valley Council", headquartersCity: "Reedsville", headquartersState: "Pennsylvania" },
  { councilNumber: 500, name: "Moraine Trails Council", headquartersCity: "Butler", headquartersState: "Pennsylvania" },
  { councilNumber: 501, name: "Northeastern Pennsylvania Council", headquartersCity: "Moosic", headquartersState: "Pennsylvania" },
  { councilNumber: 502, name: "Minsi Trails Council", headquartersCity: "Lehigh Valley", headquartersState: "Pennsylvania" },
  { councilNumber: 504, name: "Columbia-Montour Council", headquartersCity: "Bloomsburg", headquartersState: "Pennsylvania" },
  { councilNumber: 509, name: "Bucktail Council", headquartersCity: "Du Bois", headquartersState: "Pennsylvania" },
  { councilNumber: 512, name: "Westmoreland-Fayette Council", headquartersCity: "Greensburg", headquartersState: "Pennsylvania" },
  { councilNumber: 524, name: "Pennsylvania Dutch Council", headquartersCity: "Lancaster", headquartersState: "Pennsylvania" },
  { councilNumber: 525, name: "Cradle of Liberty Council", headquartersCity: "Philadelphia", headquartersState: "Pennsylvania" },
  { councilNumber: 527, name: "Laurel Highlands Council", headquartersCity: "Pittsburgh", headquartersState: "Pennsylvania" },
  { councilNumber: 528, name: "Hawk Mountain Council", headquartersCity: "Reading", headquartersState: "Pennsylvania" },
  { councilNumber: 532, name: "French Creek Council", headquartersCity: "Erie", headquartersState: "Pennsylvania" },
  { councilNumber: 533, name: "Susquehanna Council", headquartersCity: "Williamsport", headquartersState: "Pennsylvania" },
  { councilNumber: 538, name: "Chief Cornplanter Council", headquartersCity: "Warren", headquartersState: "Pennsylvania" },
  { councilNumber: 539, name: "Chester County Council", headquartersCity: "Exton", headquartersState: "Pennsylvania" },
  { councilNumber: 544, name: "New Birth of Freedom Council", headquartersCity: "Mechanicsburg", headquartersState: "Pennsylvania" },
  { councilNumber: 546, name: "Narragansett Council", headquartersCity: "East Providence", headquartersState: "Rhode Island" },
  { councilNumber: 549, name: "Palmetto Area Council", headquartersCity: "Spartanburg", headquartersState: "South Carolina" },
  { councilNumber: 550, name: "Coastal Carolina Council", headquartersCity: "Charleston", headquartersState: "South Carolina" },
  { councilNumber: 551, name: "Blue Ridge Council", headquartersCity: "Greenville", headquartersState: "South Carolina" },
  { councilNumber: 553, name: "Indian Waters Council", headquartersCity: "Columbia", headquartersState: "South Carolina" },
  { councilNumber: 556, name: "Cherokee Area Council", headquartersCity: "Chattanooga", headquartersState: "Tennessee" },
  { councilNumber: 557, name: "Great Smoky Mountain Council", headquartersCity: "Knoxville", headquartersState: "Tennessee" },
  { councilNumber: 558, name: "Chickasaw Council", headquartersCity: "Memphis", headquartersState: "Tennessee" },
  { councilNumber: 559, name: "West Tennessee Area Council", headquartersCity: "Jackson", headquartersState: "Tennessee" },
  { councilNumber: 560, name: "Middle Tennessee Council", headquartersCity: "Nashville", headquartersState: "Tennessee" },
  { councilNumber: 561, name: "Texas Trails Council", headquartersCity: "Abilene", headquartersState: "Texas" },
  { councilNumber: 562, name: "Golden Spread Council", headquartersCity: "Amarillo", headquartersState: "Texas" },
  { councilNumber: 564, name: "Capitol Area Council", headquartersCity: "Austin", headquartersState: "Texas" },
  { councilNumber: 567, name: "Buffalo Trail Council", headquartersCity: "Midland", headquartersState: "Texas" },
  { councilNumber: 571, name: "Circle Ten Council", headquartersCity: "Dallas", headquartersState: "Texas" },
  { councilNumber: 574, name: "Bay Area Council", headquartersCity: "Galveston", headquartersState: "Texas" },
  { councilNumber: 576, name: "Sam Houston Area Council", headquartersCity: "Houston", headquartersState: "Texas" },
  { councilNumber: 577, name: "South Texas Council", headquartersCity: "Corpus Christi", headquartersState: "Texas" },
  { councilNumber: 578, name: "Three Rivers Council", headquartersCity: "Beaumont", headquartersState: "Texas" },
  { councilNumber: 583, name: "Alamo Area Council", headquartersCity: "San Antonio", headquartersState: "Texas" },
  { councilNumber: 584, name: "Caddo Area Council", headquartersCity: "Texarkana", headquartersState: "Texas" },
  { councilNumber: 585, name: "East Texas Area Council", headquartersCity: "Tyler", headquartersState: "Texas" },
  { councilNumber: 587, name: "Northwest Texas Council", headquartersCity: "Wichita Falls", headquartersState: "Texas" },
  { councilNumber: 590, name: "Crossroads of the West Council", headquartersCity: "Ogden", headquartersState: "Utah" },
  { councilNumber: 592, name: "Green Mountain Council", headquartersCity: "Waterbury", headquartersState: "Vermont" },
  { councilNumber: 595, name: "Colonial Virginia Council", headquartersCity: "Newport News", headquartersState: "Virginia" },
  { councilNumber: 596, name: "Tidewater Council", headquartersCity: "Virginia Beach", headquartersState: "Virginia" },
  { councilNumber: 598, name: "Shenandoah Area Council", headquartersCity: "Winchester", headquartersState: "Virginia" },
  { councilNumber: 599, name: "Blue Ridge Mountains Council", headquartersCity: "Roanoke", headquartersState: "Virginia" },
  { councilNumber: 602, name: "Heart of Virginia Council", headquartersCity: "Richmond", headquartersState: "Virginia" },
  { councilNumber: 604, name: "Blue Mountain Council", headquartersCity: "Kennewick", headquartersState: "Washington" },
  { councilNumber: 606, name: "Mount Baker Council", headquartersCity: "Everett", headquartersState: "Washington" },
  { councilNumber: 609, name: "Chief Seattle Council", headquartersCity: "Seattle", headquartersState: "Washington" },
  { councilNumber: 610, name: "Great Alaska Council", headquartersCity: "Anchorage", headquartersState: "Alaska" },
  { councilNumber: 611, name: "Inland Northwest Council", headquartersCity: "Spokane", headquartersState: "Washington" },
  { councilNumber: 612, name: "Pacific Harbors Council", headquartersCity: "Tacoma", headquartersState: "Washington" },
  { councilNumber: 615, name: "Mountaineer Area Council", headquartersCity: "Fairmont", headquartersState: "West Virginia" },
  { councilNumber: 617, name: "Buckskin Council", headquartersCity: "Charleston", headquartersState: "West Virginia" },
  { councilNumber: 620, name: "Glacier's Edge Council", headquartersCity: "Madison", headquartersState: "Wisconsin" },
  { councilNumber: 624, name: "Gateway Area Council", headquartersCity: "La Crosse", headquartersState: "Wisconsin" },
  { councilNumber: 627, name: "Samoset Council", headquartersCity: "Weston", headquartersState: "Wisconsin" },
  { councilNumber: 635, name: "Bay-Lakes Council", headquartersCity: "Appleton", headquartersState: "Wisconsin" },
  { councilNumber: 636, name: "Three Harbors Council", headquartersCity: "Milwaukee", headquartersState: "Wisconsin" },
  { councilNumber: 637, name: "Chippewa Valley Council", headquartersCity: "Eau Claire", headquartersState: "Wisconsin" },
  { councilNumber: 640, name: "Greater New York Councils", headquartersCity: "New York", headquartersState: "New York" },
  { councilNumber: 651, name: "Potawatomi Area Council", headquartersCity: "Waukesha", headquartersState: "Wisconsin" },
  { councilNumber: 653, name: "Great Rivers Council", headquartersCity: "Columbia", headquartersState: "Missouri" },
  { councilNumber: 660, name: "Blackhawk Area Council", headquartersCity: "Rockford", headquartersState: "Illinois" },
  { councilNumber: 661, name: "Puerto Rico Council", headquartersCity: "Guaynabo", headquartersState: "Puerto Rico" },
  { councilNumber: 662, name: "Longhorn Council", headquartersCity: "Hurst", headquartersState: "Texas" },
  { councilNumber: 664, name: "Suwannee River Area Council", headquartersCity: "Tallahassee", headquartersState: "Florida" },
  { councilNumber: 690, name: "Garden State Council", headquartersCity: "Westampton", headquartersState: "New Jersey" },
  { councilNumber: 694, name: "South Plains Council", headquartersCity: "Lubbock", headquartersState: "Texas" },
  { councilNumber: 695, name: "Black Hills Area Council", headquartersCity: "Rapid City", headquartersState: "South Dakota" },
  { councilNumber: 696, name: "Midnight Sun Council", headquartersCity: "Fairbanks", headquartersState: "Alaska" },
  { councilNumber: 697, name: "Pacific Crest Council", headquartersCity: "Eugene", headquartersState: "Oregon" },
  { councilNumber: 702, name: "Rainbow Council", headquartersCity: "Morris", headquartersState: "Illinois" },
  { councilNumber: 713, name: "Sequoyah Council", headquartersCity: "Johnson City", headquartersState: "Tennessee" },
  { councilNumber: 733, name: "Sioux Council", headquartersCity: "Sioux Falls", headquartersState: "South Dakota" },
  { councilNumber: 741, name: "Texas Southwest Council", headquartersCity: "San Angelo", headquartersState: "Texas" },
  { councilNumber: 748, name: "Natchez Trace Council", headquartersCity: "Tupelo", headquartersState: "Mississippi" },
  { councilNumber: 763, name: "Virginia Headwaters Council", headquartersCity: "Waynesboro", headquartersState: "Virginia" },
  { councilNumber: 773, name: "Gulf Coast Council", headquartersCity: "Pensacola", headquartersState: "Florida" },
  { councilNumber: 775, name: "Rio Grande Council", headquartersCity: "Harlingen", headquartersState: "Texas" },
  { councilNumber: 777, name: "Washington Crossing Council", headquartersCity: "Doylestown", headquartersState: "Pennsylvania" },
  { councilNumber: 780, name: "Michigan Crossroads Council", headquartersCity: "Eagle", headquartersState: "Michigan" },
  { councilNumber: 800, name: "Direct Service", headquartersCity: "Irving", headquartersState: "Texas" },
  { councilNumber: 802, name: "Transatlantic Council", headquartersCity: "Brussels", headquartersState: null },
  { councilNumber: 803, name: "Far East Council", headquartersCity: "Camp Zama", headquartersState: null },
];

async function main() {
  console.log(`Seeding ${COUNCILS.length} councils...`);

  let inserted = 0;
  let errors = 0;

  for (const council of COUNCILS) {
    try {
      await db
        .insert(schema.councils)
        .values(council)
        .onConflictDoUpdate({
          target: schema.councils.councilNumber,
          set: {
            name: council.name,
            headquartersCity: council.headquartersCity,
            headquartersState: council.headquartersState,
          },
        });
      inserted++;
    } catch (err) {
      console.error(`Error inserting council ${council.councilNumber} (${council.name}):`, err);
      errors++;
    }
  }

  console.log(`Done. Inserted/updated: ${inserted}, Errors: ${errors}`);
  process.exit(errors > 0 ? 1 : 0);
}

main().catch((err) => {
  console.error("Fatal error:", err);
  process.exit(1);
});
